#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx6g -XX:+UseG1GC

#Gradle
org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.workers.max=2

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true

#MPP
kotlin.mpp.enableCInteropCommonization=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
